title: Untitled
output:
  general:
    input: true
    input_jinja: false
    output: true
    output_error: false
    output_stdout: true
  html:
    toc: true
    toc_depth: 3
    toc_collapsed: true
    toc_smooth_scroll: true
    toc_extend_page: true
    number_sections: false
    code_folding: hide
    code_tools: false
    tabset: true
    theme: paper
    include_plotlyjs: true
  pdf:
    toc: true
    toc_depth: 3
    language: english
